### ISSUE TITLE
Secp256k1

### ISSUE THREAD

**Issue by cockerfly** [dmazzella/ucrypto#13]
Hi!
Can I use calculations with the secp256k1 curve if I change the source data in the file "ucrypto_ecc_p256.py"?

**Comment by dmazzella** [comment]
Hi,
Yes you can copy values from [fastecdsa](https://github.com/AntonKueltz/fastecdsa/blob/44c86a7aab649f3b17223f3dd295ff5625cb919b/fastecdsa/curve.py#L210)

**Comment by cockerfly** [comment]
> Hi, Yes you can copy values from [fastecdsa](https://github.com/AntonKueltz/fastecdsa/blob/44c86a7aab649f3b17223f3dd295ff5625cb919b/fastecdsa/curve.py#L210)

Thank you, dear friend!))

**Comment by dmazzella** [comment]
Happy coding 😉
