### ISSUE TITLE
make on Pi Pico RP2040 board

### ISSUE THREAD

**Issue by cockerfly** [dmazzella/ucrypto#14]
Hi, friend!) 
What is the right command to make firmware on Pi Pico 2040 board? When i used this ->  make -j8 -C mpy-cross && make -j8 -C ports/stm32/ BOARD="PYBD_SF6" USER_C_MODULES="$(pwd)/ports/stm32/boards/PYBD_SF6/cmodules"  firmware.elf is not supported. And when i convert this firmware with ./elf2uf2 firmware.elf firmware.uf2  I get an error "ERROR: HARD-FLOAT not supported"

Please help me to understand this

**Comment by dmazzella** [comment]
Hi, try this:

clone ucrypto into `RPI_PICO/cmodules/ucrypto`:
```bash
micropython (master) ✗ git clone https://github.com/dmazzella/ucrypto.git $(pwd)/ports/rp2/boards/RPI_PICO/cmodules/ucrypto
```

edit `ports/rp2/boards/manifest.py` at the and of file add:

```python
include("$(BOARD_DIR)/cmodules/ucrypto/modules")
```

build `RPI_PICO`:

```bash
micropython (master) ✗ make -j8 -C mpy-cross && make -j8 -C ports/rp2 BOARD=RPI_PICO USER_C_MODULES="$(pwd)/ports/rp2/boards/RPI_PICO/cmodules/ucrypto/micropython.cmake"
```

**Comment by cockerfly** [comment]
> 

I did everything you said, in the end an error still appears

CMake Error: The source directory "/home/ldb/pico/pico-examples/build/micropython/ports/rp2/build-RPI_PICO" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:54: recipe for target 'all' failed
make: *** [all] Error 1
![Снимок экрана от 2023-08-30 18-03-47](https://github.com/dmazzella/ucrypto/assets/54579209/d54cfc07-b917-4451-a8c4-8a921711b390)

**Comment by dmazzella** [comment]
Are you on the MicroPython master?

**Comment by cockerfly** [comment]
> 
I think yes))
![Снимок экрана от 2023-08-30 18-37-31](https://github.com/dmazzella/ucrypto/assets/54579209/48cbd182-af67-427d-a15d-2a24aa71c85a)

**Comment by dmazzella** [comment]
Have you cloned a fresh micropython repo? have you initialized submodules?

`git submodule update --init --depth 1`

**Comment by cockerfly** [comment]
> Have you cloned a fresh micropython repo? have you initialized submodules?
> 
> `git submodule update --init --depth 1`

Yes. I did everything according to the instructions on the main page of the repo. Specifically this command --> "git submodule update --init"

**Comment by dmazzella** [comment]
Have you tried a clean build without ucrypto?

Try first a clean build and if it succeded include the ucrypto module

**Comment by cockerfly** [comment]
> Have you tried a clean build without ucrypto?
> 
> Try first a clean build and if it succeded include the ucrypto module

I'll try like this, thanks for help))

**Comment by cockerfly** [comment]
> > Have you tried a clean build without ucrypto?
> > Try first a clean build and if it succeded include the ucrypto module
> 
> I'll try like this, thanks for help))

Clean build also print error(
![Снимок экрана от 2023-08-31 14-21-39](https://github.com/dmazzella/ucrypto/assets/54579209/d0300261-6f71-4829-b73f-297dcfbbd3b9)

**Comment by cockerfly** [comment]
> Have you tried a clean build without ucrypto?
> 
> Try first a clean build and if it succeded include the ucrypto module

The main cause of the error was ubuntu of the old version. When I installed 22.04, everything worked immediately. Thanks again for the tips and good luck!
The topic can be closed)

**Comment by dmazzella** [comment]
glad you solved it, good luck to you
