### ISSUE TITLE
[ESP32]: Building with TFM optimizations on XTENSA results in "dangerous relocation" linker errors.

### ISSUE THREAD

**Issue by RSC-Games** [dmazzella/ucrypto#20]
I enabled optimizations for ECDSA and RSA and compiled the project. It builds fine without the optimizations but with them I get these linker errors (for every single function?)
![image](https://github.com/user-attachments/assets/459f1660-d78f-4e62-97e6-3a2d3910b076)

**Comment by RSC-Games** [comment]
NOTE: Using the compiler flag `-mtext-section-literals` did not help matters and made them far worse.
![image](https://github.com/user-attachments/assets/447806fd-170f-49e3-99eb-ee062b457534)

**Comment by dmazzella** [comment]
XTENSA is not an arch supported for asm optimizations

**Comment by dmazzella** [comment]
If you need optimizations, please switch to [ucryptography](https://github.com/dmazzella/ucryptography.git)

**Comment by RSC-Games** [comment]
Okay I probably should have checked that. I could write my own but that would take quite a while
