### ISSUE TITLE
implement ed25519 for micropython

### ISSUE THREAD

**Issue by abuvanth** [dmazzella/ucrypto#4]

**Comment by dmazzella** [comment]
@abuvanth 

the math needed is available, I don't have time to implement it, you can take inspiration from [ed25519](https://github.com/pyca/ed25519) for a simple implementation to bring back to ucrypto

**Comment by abuvanth** [comment]
@dmazzella Okay I will look into it

**Comment by abuvanth** [comment]
ed25519 ported for micropython here - https://github.com/abuvanth/millegrilles.rpipico/blob/master/millegrilles/src/oryx_crypto.c

**Comment by abuvanth** [comment]
i am using https://github.com/abuvanth/millegrilles.rpipico/blob/master/millegrilles/src/oryx_crypto.c as ed25519 implementation. hence closed this issue
