### ISSUE TITLE
hashlib.md5() seems to be removed in latest uhashlib

### ISSUE THREAD

**Issue by y3k00000** [dmazzella/ucrypto#8]
As title, found this issue when installing .py files to my pico_w.

I currently comment out the occurrences of hashlib.md5 to make it work.

**Comment by y3k00000** [comment]
from [Document](https://docs.micropython.org/en/v1.15/library/uhashlib.html)

`MD5 - A legacy algorithm, not considered cryptographically secure. Only selected boards, targeting interoperability with legacy applications, will offer this.` 

I think this is another board supporting issue.

**Comment by MATTYGILO** [comment]
Hi @y3k00000 have you yet gotten this to work, I tried this repo back in the day. It seemed to not work at all even if you compiled it and put it on a device?

**Comment by y3k00000** [comment]
@MATTYGILO After the u2f was built and uploaded to the board you'll need to manually copy files from [Here](https://github.com/dmazzella/ucrypto/tree/master/modules) into the board's /lib directory.

If hashlib on your board doesn't provide the md5() then you'll have to edit the copied py files and comment out all md5() related calls.

Then you can begin importing the module and see if it's working.
![image](https://user-images.githubusercontent.com/3966578/207481066-99162715-3e75-46bf-8c97-2d36fc52a19f.png)

**Comment by dmazzella** [comment]
solved in [eba2c08](https://github.com/dmazzella/ucrypto/commit/eba2c080352a76e912dc8a057c86c01bb1c46259)

**Comment by dmazzella** [comment]
@y3k00000 if you can confirm that it works we can close the issue, tnx

**Comment by y3k00000** [comment]
@dmazzella The importing is ok now. 👍
![image](https://user-images.githubusercontent.com/3966578/207713833-802f7f2e-ffd3-4fdb-b8c4-ca30b319d0c3.png)

But when I tried running ecdsa test
![image](https://user-images.githubusercontent.com/3966578/207715499-58f4c0dc-e6eb-40e7-b0f2-4c8f2536a459.png)

It seems a further fix is required.

**Comment by dmazzella** [comment]
fixed in [ffbd73](https://github.com/dmazzella/ucrypto/commit/ffbd73e0241b9c8760a1be335b168e0ae9c41671)

**Comment by y3k00000** [comment]
Tested and it's ok now.
