### ISSUE TITLE
THIS REPO DOESN'T WORK! YOU HAVEN'T EVEN TRIED IT ON A DEVICE HAVE YOU!

### ISSUE THREAD

**Issue by MATTYGILO** [dmazzella/ucrypto#9]

**Comment by dmazzella** [comment]
This is not a proper way to collaborate on an open source project, instead of writing untrue things maybe it would be more productive to detail the problems, maybe look for a solution and help keep the project alive

**Comment by y3k00000** [comment]
@MATTYGILO 

I believe dmazzella had at least tried his works on a pyboard. And that doesn't means every other boards that micropython supports will be working naturally. Every boards would have limitations or difference in their design. So don't think that he should be responsible to every boards, that would be a ridiculously non-sense.

In case you probably don't notice, I've reported some issues that I met on pico-w board and he tried helping. Perhaps you should state your problem like I did, that helps more between everybody.

@dmazzella Thanks for the help, have a nice day.

**Comment by MATTYGILO** [comment]
> This is not a proper way to collaborate on an open source project, instead of writing untrue things maybe it would be more productive to detail the problems, maybe look for a solution and help keep the project alive

Sorry please forgive me, I was very annoyed after trying to get this repo to work many times over months. I understand I shouldn't have raised an issue like this.
